export const quotes = [
  "Action precedes motivation.",
  "You don't have to feel like it to do it.",
  "The hardest part is standing up.",
  "Five minutes of discomfort beats a day of regret.",
  "Stop negotiating with yourself.",
  "Momentum builds the moment you move.",
  "Do it now. Sometimes 'later' becomes 'never'.",
  "Great things never come from comfort zones.",
  "Discipline equals freedom.",
  "Don't stop when you're tired. Stop when you're done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "If it matters to you, you'll find a way.",
  "Success starts with self-discipline.",
  "Your mind will quit a thousand times before your body does.",
  "Doubt kills more dreams than failure ever will.",
  "Focus on your goals, not your fear.",
  "Don't wait for opportunity. Create it.",
  "Procrastination is the thief of time.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "Suffer the pain of discipline or suffer the pain of regret.",
  "Results happen over time, not overnight.",
  "You are what you do, not what you say you'll do.",
  "Start where you are. Use what you have. Do what you can.",
  "It's going to be hard, but hard does not mean impossible.",
  "Don't watch the clock; do what it does. Keep going.",
  "The secret of getting ahead is getting started.",
  "Excuses don't get results.",
  "Dream big and dare to fail.",
  "Make your life a masterpiece; imagine no limitations on what you can be, have or do.",
  "Push yourself, because no one else is going to do it for you.",
  "Sometimes later becomes never. Do it now.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Dream it. Wish it. Do it.",
  "Success doesn't just find you. You have to go out and get it.",
  "Little things make big days.",
  "It's not about perfect. It's about effort.",
  "Make each day your masterpiece.",
  "The difference between ordinary and extraordinary is that little extra.",
  "Believe in yourself and all that you are.",
  "Success is what happens after you have survived all of your mistakes.",
  "A year from now you may wish you had started today.",
  "Don't wait to strike till the iron is hot, but make it hot by striking.",
  "Whether you think you can or think you can't, you're right.",
  "The only place where success comes before work is in the dictionary.",
  "Nothing will work unless you do.",
  "Action is the foundational key to all success.",
  "It always seems impossible until it's done.",
  "Energy and persistence conquer all things.",
  "You can't cross the sea merely by standing and staring at the water.",
  "Someday is not a day of the week.",
  "Even if you fall on your face, you're still moving forward.",
  "We generate fears while we sit. We overcome them by action.",
  "You don't cross limits without pushing past them.",
  "An inch of movement will bring you closer to your goals.",
  "Don't fear failure. Fear being in the exact same place next year.",
  "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.",
  "Things may come to those who wait, but only the things left by those who hustle.",
  "I find that the harder I work, the more luck I seem to have.",
  "Do or do not. There is no try.",
  "Opportunity is missed by most people because it is dressed in overalls and looks like work.",
  "A river cuts through rock not because of its power but its persistence.",
  "Do one thing every day that scares you.",
  "If you're going through hell, keep going.",
  "There are no shortcuts to any place worth going.",
  "Don't quit. Suffer now and live the rest of your life as a champion.",
  "I will beat her. I will train harder. I will eat cleaner. I know her strengths. I’ve lost to her before but not this time. She is going down. I have the advantage because I know her well. She is the old me.",
  "Obstacles are those frightful things you see when you take your eyes off your goal.",
  "Your life does not get better by chance, it gets better by change.",
  "Do today what others won't, so tomorrow you can do what others can't.",
  "I attributes my success to this: I never gave or took any excuse.",
  "The best revenge is massive success.",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
  "Strive for progress, not perfection.",
  "Only I can change my life. No one can do it for me.",
  "There is no elevator to success, you have to take the stairs.",
  "A goal without a plan is just a wish.",
  "If you don't build your dream, someone else will hire you to help them build theirs.",
  "The future depends on what you do today.",
  "Focus on being productive instead of busy.",
  "Failure will never overtake me if my determination to succeed is strong enough.",
  "Do what you have to do until you can do what you want to do.",
  "Don't limit your challenges. Challenge your limits.",
  "You cannot perform in a manner inconsistent with the way you see yourself.",
  "We become what we think about.",
  "The successful warrior is the average man, with laser-like focus.",
  "The man who moves a mountain begins by carrying away small stones.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "What you lack in talent can be made up with desire, hustle and giving 110% all the time.",
  "Do not let what you cannot do interfere with what you can do.",
  "To begin, begin.",
  "I didn't get there by wishing for it or hoping for it, but by working for it.",
  "You measure the size of the accomplishment by the obstacles you had to overcome.",
  "Real difficulties can be overcome; it is only the imaginary ones that are unconquerable.",
  "Effort only fully releases its reward after a person refuses to quit.",
  "If there is no struggle, there is no progress.",
  "Strength does not come from winning.",
  "He who is not courageous enough to take risks will accomplish nothing.",
  "Do small things with great love.",
  "Your only limit is you."
];

export const getRandomQuote = () => quotes[Math.floor(Math.random() * quotes.length)];